site_name: java
docs_dir: ./docs

nav:
  - WireMock Java: index.md
  - v4 Beta: v4_beta.md
  - Getting started:
    - Overview: getting_started/overview.md
    - Quick Start API Mocking with Java and JUnit 4: getting_started/quick_start_api_mocking_with_java_junit_4.md
    - Download and Install: getting_started/download_and_installation.md
    - WireMock Tutorials: getting_started/wiremock_tutorials.md
    - Frequently Asked Questions: getting_started/frequently_asked_questions.md
    - Community Resources: getting_started/community_resources.md

  - Running Wiremock: 
    - WireMock standalone service: running_wiremock/wiremock_standalone_service.md
    - Running in docker: running_wiremock/running_in_docker.md
    - Running as a standalone process: running_wiremock/running_as_a_standalone_process.md
    - Administration API: running_wiremock/administration_api.md

  - Java Usage:
    - WireMock for Java and JVM languages: java_usage/wiremock_for_java_and_jvm_languages.md
    - JUnit 5+ Jupiter: java_usage/junit_5_plus_jupiter.md
    - JUnit 4 and Vintage: java_usage/junit_4_and_vintage.md
    - Plain Java: java_usage/plain_java.md
    - Java configuration: java_usage/java_configuration.md
    - Running without the HTTP Server: java_usage/runnint_without_the_http_server.md
    - Using WireMock with Jetty 12: java_usage/using_wiremock_with_jetty_12.md

  - Stubbing and Verifying:
    - Stubbing: stubbing_and_verifying/stubbing.md
    - Request Matching: stubbing_and_verifying/request_matching.md
    - Response Templating: stubbing_and_verifying/response_templating.md
    - Simulating Faults: stubbing_and_verifying/simulating_faults.md
    - Stateful Behaviour: stubbing_and_verifying/stateful_behaviour.md
    - Proxying: stubbing_and_verifying/proxying.md
    - Verifying: stubbing_and_verifying/verifying.md

  - Mock API Templates Library:
    - WireMock API Templates Library: mock_api_template_library/wiremock_api_template_library.md
    - Using Mock API Templates: mock_api_template_library/using_mock_api_templates.md

  - Record and Playback:
    - Record and Playback: record_and_playback/record_and_playback.md

  - Protocols:
    - Webhooks and Callbacks: protocols/webhooks_and_callbacks.md
    - Mocking gRPC services: protocols/mocking_grpc_services.md
    - WireMock and GraphQL: solutions/graphql.md
    - JSON Web Tokens (JWT): protocols/json_web_tokens.md
    - Serving HTTPS: protocols/serving_https.md

  - Integrations:
    - WireMock Spring Boot Integration: integrations/wiremock_spring_boot_integration.md

  - Advanced use-cases:
    - Multi-domain Mocking: advanced_use_cases/multidomain_mocking.md
    - Deploying into a servlet container: advanced_use_cases/deploying_into_a_servlet_container.md
    - WireMock on Java 1.7: advanced_use_cases/wiremock_on_java.md

  - Extensibility:
    - Extending WireMock: extensibility/extending_wiremock.md
    - Filtering and Modifying Requests: extensibility/filtering_and_modifying_requests.md
    - Transforming Responses: extensibility/transforming_responses.md
    - Custom Matching: extensibility/custom_matching.md
    - Listening for Serve Events: extensibility/listening_for_serve_events.md
    - Admin API Extensions: extensibility/admin_api_extensions.md
    - Adding Template Helpers: extensibility/adding_template_helpers.md
    - Adding Template Model Data: extensibility/adding_template_model_data.md
    - Listening for Stub Changes: extensibility/listening_for_stub_changes.md
    - Listening for Settings Changes: extensibility/listening_for_setting_changes.md
    - Mappings Loader Extensions: extensibility/mapping_loader_extensions.md
    - Stub Metadata: extensibility/stub_metadata.md

  - Solutions:
    - Running on Android: solutions/android.md
    - WireMock and C/C++: solutions/c_cpp.md
    - WireMock and .NET: solutions/dotnet.md
    - WireMock and Go: solutions/golang.md
    - WireMock and GraphQL: solutions/graphql.md
    - WireMock and Groovy: solutions/groovy.md
    - WireMock for Java and JVM languages: solutions/jvm.md
    - WireMock and Kotlin: solutions/kotlin.md
    - WireMock and Kubernetes: solutions/kubernetes.md
    - WireMock and Node.js: solutions/nodejs.md
    - Using WireMock with Pact: solutions/pact.md
    - WireMock and Python: solutions/python.md
    - WireMock and Quarkus: solutions/quarkus.md
    - WireMock and Rust: solutions/rust.md
    - Using WireMock with Spring Boot: solutions/spring-boot-integration.md
    - WireMock and Testcontainers: solutions/testcontainers.md


  - Reference:
    - Admin API: reference/admin-api-reference.md
    - WireMock API Templates Library: reference/mock-api-templates.md

  - Commercial Support: commercial.md
  - Support: support.md
  


