INHERIT: nav.yml
site_name: WireMock

site_description: WireMock is a flexible API mocking tool for fast, robust and comprehensive testing.
site_author: Tom Akehurst


theme:
  custom_dir: overrides
  font: 
    text: DM Sans
    code: Source Code Pro
  name: material
  palette:
    scheme: wiremock
  logo: assets/images/logo_wide.svg
  locale: en
  features:
    - navigation.instant
    - navigation.path
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky



markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      line_spans: __span
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'docs/'
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - monorepo
  - search
  - macros
  - mkdocs-breadcrumbs-plugin:
      delimiter: " / "
      log_level: "ERROR"
      exclude_paths:
        - "docs/**"
      generate_home_index: false
      use_page_titles: false 
      home_text: "Documentation"
  - redirects:
      redirect_maps:
        'index.md': 'java/index.md'
        

extra:
  wiremock_version: 3.13.1
  wiremock_4_version: 4.0.0-beta.10
  grpc_extension_version: 0.11.0
  spring_boot_integration_version: 3.10.0

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/sidebar-search.js

watch:
  - docs
  - overrides